name: reth-prysm
# Reth (EL) + Prysm (CL)
# Both Rust/Go performance-oriented clients.
spec:
  execution:
    client: reth
    image: ghcr.io/paradigmxyz/reth:v1.1.0
    dataDir: /data/execution
    flags:
      chain: mainnet
      datadir: /data/execution
      http: "true"
      http.addr: "127.0.0.1"
      http.port: "8545"
      http.api: "eth,net,web3,engine,admin,txpool"
      authrpc.addr: "127.0.0.1"
      authrpc.port: "8551"
      authrpc.jwtsecret: /data/jwtsecret
      metrics: "127.0.0.1:6060"
    ports:
      http: 8545
      p2p: 30303
      metrics: 6060

  consensus:
    client: prysm
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.1.0
    dataDir: /data/consensus
    flags:
      mainnet: "true"
      execution-endpoint: http://127.0.0.1:8551
      jwt-secret: /data/jwtsecret
      checkpoint-sync-url: https://beaconstate.info
      genesis-beacon-api-url: https://beaconstate.info
      rpc-host: "127.0.0.1"
      grpc-gateway-host: "127.0.0.1"
      grpc-gateway-port: "5052"
      monitoring-host: "127.0.0.1"
      monitoring-port: "5054"
      p2p-tcp-port: "9000"
      accept-terms-of-use: "true"
    ports:
      http: 5052
      p2p: 9000
      metrics: 5054
